### ISSUE TITLE
Needs special symbols support

### ISSUE THREAD

**Issue by sem-soft** [omgovich/omgopass#13]
For some services needs special symbols support. For example,

> Password must contain at least one special character.

**Comment by omgovich** [comment]
Let's start with a discussion.
I guess that the primary question is "**which password format do should we use?**".

I guess there are several options for us:
1. A password contains characters between syllables. Like `Go6.Gi4.Mok8` or `Gu7=Ka3=Ge4`
2. A password could start and end with special characters. Like `@Go6Gi4Mok8!`
3. Both options. Generate passwords like `@Go6-Gi4-Mok8!`
4. The user could choose between these options.

P.S. Please keep in mind that the library generates memorable passwords. So it's very important to keep passwords easy-to-remember even if they contain special characters.

@molefrog Could you join us here?

**Comment by molefrog** [comment]
To me, the special symbols support sounds like an edge case. I would keep track of this request and if this is really something that every 2nd developer needs, add this to the library core. 

Meanwhile, this could be easily solved by concatenating a regular password generated with omgopass + a tiny 2-3 letter word generated with an alphabet that contains only special characters. @omgovich You can even work on a demo and include it in the README to solve 99% of the future requests.

P.S. Whether you should add this feature to the library or not is totally up to you, but IMO it all depends on the mission and motivation of the library.

**Comment by omgovich** [comment]
I think I found a good simple solution:
We can define new param `separators` (string). Developers will use this param to config a list of symbols that can be used as separators between words/syllables.

Examples:
```js
generate() // "Go6Gi4Mok8", default `separators` value is "" (no breaking changes)
generate({ separators: " " }) // "Go6 Gi4 Mok8"
generate({ separators: "-_~" }) // "Go6_Gi4~Mok8"

// Bonus feature/recipe
// OWASP-like passphrase generation: 
generate({
  minSyllableLength: 4,
  minSyllableLength: 6,
  hasNumbers: false,
  titlecased: false,
  separators: " "
}) // "podyn canu deburi"
```

@molefrog @sem-soft What do you think guys?

**Comment by sem-soft** [comment]
@omgovich sounds good!

**Comment by molefrog** [comment]
Absolutely agree! Would like also nice to add the OWASP reference to the README, it sounds like a potentially good selling point of the library.
