### ISSUE TITLE
Typescript support

### ISSUE THREAD

**Issue by Haple** [omgovich/omgopass#16]
Again, thank you for your work!

Do you plan to add support to Typescript?

**Comment by omgovich** [comment]
Hi @Haple!
Actually, I'm not going to do that, because `omgopass` is a super light library — without TS we have more control and more options to keep the library small.

**Comment by omgovich** [comment]
Although we can provide the type definition files with the package.
@Haple Would you like to help with that?

See examples:
https://github.com/molefrog/wouter#can-i-use-wouter-in-my-typescript-project
https://github.com/ai/nanoid/blob/master/index.d.ts
