### ISSUE TITLE
Password length

### ISSUE THREAD

**Issue by dmitriyeff** [omgovich/omgopass#17]
It would be nice to have some information about the generated code length in the documentation because the max/min length is not defined (haven't found that information).

It's easy to limit the length of the string, but it would be nice to have it as an additional option. Thank you!

**Comment by omgovich** [comment]
Hey @dmitriyeff 

The length is configured by several params:
```
syllablesCount
minSyllableLength
maxSyllableLength
hasNumbers
```

So the only thing we could do is to add a note that with the default settings the length is in 9-12 range.

**Comment by omgovich** [comment]
Done e1093ba
