### ISSUE TITLE
Add support for Symbols

### ISSUE THREAD

**Issue by mittalyashu** [omgovich/omgopass#18]

**Comment by omgovich** [comment]
Hey @mittalyashu. Could you please describe your suggestion?

**Comment by mittalyashu** [comment]
@omgovich Here's the example

<img width="697" alt="CleanShot 2020-10-21 at 06 22 02@2x" src="https://user-images.githubusercontent.com/29014463/96659902-cc96ed80-1365-11eb-937a-7e610b4edde1.png">

**Comment by omgovich** [comment]
Hi! The thing is omgopass is a memorable password generator.
In our case, it means that the library generates several syllables like (`Bud`, `Cup`, `Dot`).
If you need to add special characters to your password, you could use `separators` option:
https://github.com/omgovich/omgopass#available-options

Example:
```js
omgopass({ hasNumbers: false, maxSyllableLength: 5, separators: '_~-' }) // "Toc-Rot_Dim~Re-Mah"
```

**Comment by mittalyashu** [comment]
> If you need to add special characters to your password, you could use separators option:
https://github.com/omgovich/omgopass#available-options

Yes, I am aware of that, but I was more of looking for an option to add random symbols.

As you have mentioned that `omgopass` is a memorable password generator, in that case, there can be another parameter like `symbols: true` and set the default value to false.

**Comment by omgovich** [comment]
If you need to generate a random password with random symbols in random places `omgopass` probably isn't the best solution for that. We aim to generate memorable passwords and the only way to add symbols to passwords and keep them memorable is to put symbols between syllables (as we do by `separators` option).

**Comment by omgovich** [comment]
Check our benchmark to see alternatives and their size/speed. Probably one of them fits better for your task.
https://github.com/omgovich/omgopass#benchmark

If you're looking for a super tiny and fast random string generator I would suggest you check `nanoid`:
https://github.com/ai/nanoid
