### ISSUE TITLE
Add AES( Advanced Encryption Standard ) and DES ( Data Encryption Standard )

### ISSUE THREAD

**Issue by GeekyNaved** [omgovich/omgopass#19]
Kindly add AES( Advanced Encryption Standard ) and DES ( Data Encryption Standard )

**Comment by omgovich** [comment]
Hi! Could you please provide a simple spec or a code example for the API you need?

**Comment by GeekyNaved** [comment]
Sorry, I have no idea about this. I just thought it should use cryptography concept like AES or DES
